## NumPy Basics

### Credit, Thanks, and Purpose
To Shashank Kalanithi, whose warmth, courage to err and correct, knowledge, and hours of labor have gone into producing dozens of videos and Notion Documents on data science and analytics, from theory to technique -- all taught masterfully -- thank you.

I produced this notebook as a repository for my own understanding and plan to add to it as I learn more. I hope it might serve a similarly useful pedagogic purpose to others at the beginning of thier Python journey, and that those with greater expertise might correct any errors or misapprehensions they notice to help create a useful set of references that future us will be happy to have.

Much of it is based on Shashank's video "Python for Data Scientists and Data Analysts"; I strongly encourage you to support him in any way you can and make use of the explanations, documents, and courses he produces. I have found them to be invaluable resources and trust that anyone wanting to brush up on their knowledge or learn the fundamentals will as well.

https://www.youtube.com/watch?v=sZDgJKI8DAM&ab_channel=ShashankKalanithi leads to "Python for Data Scientists and Analysts" and
https://www.youtube.com/@ShashankData leads to Shashank's channel.

In [1]:
# Numpy is a mathematical library for Python which forms the foundation of many more advanced and useful libraries for data analysis...
# ... as such, a thorough understanding of it isn't required but is useful.

import numpy as np

### Arrays and Reshaping

In [2]:
# Numpy arrays are the same as Python lists, but: They are faster and are able to be manipulated by Numpy methods.

numpy_array_test = np.array([1, 3, 5, 7, 9, 11]) # <-- Note that within the parentheses, list brackets must be included.
numpy_array_test

array([ 1,  3,  5,  7,  9, 11])

In [3]:
# Numpy arrays can be reshaped from 1D arrays, as shown above, to 2D and 3D arrays (effectively tables):

numpy_array_test1 = np.array([1, 3, 5, 7, 9, 11]).reshape(2,3) # <-- 2 denotes the # of rows and 3 the # of columns
numpy_array_test1                                              # .reshape is attached to the array to actiate the reformatting

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [4]:
numpy_array_test3 = np.array([1, 3, 5, 7, 9, 11, 13, 15]).reshape(2,2,2) # <- 2 rows, 2 columns, in 2 tables
numpy_array_test3

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]]])

### Numpy Arithmetic Methods

In [5]:
q = np.array([1,2,3,4,5,6])

print(q.sum())
print(q.min())
print(q.max())
print(q.mean())
print(q.std())

21
1
6
3.5
1.707825127659933


### Numpy Special Arrays

In [6]:
np.zeros(5)                 # Creates an array of zeros with 5 elements


array([0., 0., 0., 0., 0.])

In [7]:
np.linspace(0, 5, 10)       # Creates an array of values from 0 through 5 in 10 even spaces

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
np.random.rand(5)           # Three random values between 0 and 1

array([0.67603805, 0.44513761, 0.64302085, 0.18778945, 0.38318011])

In [9]:
np.random.randint(1, 100)  # Generates a random integer between 1 and 100

72

In [10]:
np.arange(5)               # Provides a range of integers from x-y, in this case 0-5, since the beginning was unspecified.
                             # Range beginnings and end are separated by comma. ( , )

array([0, 1, 2, 3, 4])